// My parks resource


const parks = [
   {name: "St George", city: "Bristol", foodAndBeverage: "The Bake Box with outdoor seating area", parking: false, toilets: true,  disableAccess: true, imgs: ["https://visitbristol.co.uk/imageresizer/?image=%2fdmsimgs%2fWheels%20area_1881941247.jpg&action=ProductDetail","https://live.staticflickr.com/4007/4328425741_39f3f427d0_b.jpg","http://www.bristolyogabliss.co.uk/wp-content/uploads/2011/08/IMG_0729.jpg"]},
   {name: "Castle Park", city: "Bristol", foodAndBeverage: "Vegan kiosk with outdoor seating area", parking: false, toilets: true,  disableAccess: true, imgs: ["https://epigram.org.uk/content/images/2019/03/Castle.park.bristol.arp-3.jpg","https://64.media.tumblr.com/tumblr_lzjgg7zqNF1rpi86go4_1280.jpg","https://i2-prod.bristolpost.co.uk/incoming/article4069823.ece/ALTERNATES/s1227b/0_JK_BR_220420castle-park015JPG.jpg"]},
   {name: "Victoria Park", city: "Bristol", foodAndBeverage: "Stuffed's café", parking: false, toilets: true,  disableAccess: true, imgs: ["https://mr3.homeflow-assets.co.uk/files/site_asset/image/3123/6419/_x_/Car5_VictoriaPark_IMG_0309.jpg","https://static.thousandwonders.net/Royal.Victoria.Park.original.25608.jpg"]},
   {name: "Arnos Vale Cementery", city: "Bristol", foodAndBeverage: "Atrium Café", parking: true, toilets: true,  disableAccess: true, imgs: ["https://a.travel-assets.com/findyours-php/viewfinder/images/res70/298000/298999-Arnos-Vale-Cemetery.jpg","https://www.bristolwalkfest.com/wp-content/uploads/2021/04/Arnos-Vale-Cemetery-aerial-view-copyright-Arnos-Vale-Cemetery.jpg","https://www.montfortconsultants.com/wp-content/uploads/2018/08/IMG_7832.jpg","https://arnosvale.org.uk/wp-content/uploads/2019/01/anglican-chapel-venue-bristol-hero.jpg"]},
   {name: "Brandon Hill Nature Park", city: "Bristol", foodAndBeverage: null, parking: false, toilets: true,  disableAccess: true, imgs: ["http://photos.wikimapia.org/p/00/03/18/71/89_full.jpg","https://lh4.ggpht.com/-QSBqeGCwY6E/U3M9l9AJVCI/AAAAAAAAABo/RZeCXQuq3cU/s1600/DSC_0208.JPG","https://i.pinimg.com/originals/7b/8e/76/7b8e763af6b103d07c4d401d02bfdeec.jpg","http://4.bp.blogspot.com/-DrElpbSIfn4/UtwOXLesMZI/AAAAAAAABFk/i8laioAxZu0/s1600/DSCN0897.JPG"]},
   {name: "Netham Park", city: "Bristol", foodAndBeverage: null, parking: true, toilets: true,  disableAccess: false, imgs: ["https://www.freeparks.co.uk/wp-content/uploads/2016/01/netham-3.jpg","https://cached.imagescaler.hbpl.co.uk/resize/scaleWidth/885/cached.offlinehbpl.hbpl.co.uk/news/WOH/Netham-Park-BristolCRED-Andrew-Bennett-Flickr-20170626014440158.jpg","https://live.staticflickr.com/65535/49887315132_c4c5ab5a86_b.jpg"]},
   {name: "St Agnes Park", city: "Bristol", foodAndBeverage: null, parking: false, toilets: false,  disableAccess: true, imgs: ["https://bristol.cityofsanctuary.org/wp-content/uploads/sites/14/2018/03/St-Agnes-Park.jpg","https://i2-prod.bristolpost.co.uk/incoming/article794942.ece/ALTERNATES/s615b/BRML20171117D-010_CJPG.jpg","https://mr1.homeflow-assets.co.uk/files/site_asset/image/3117/6318/_x_/Car3_StAgnes_IMG_0135.jpg"]},
   {name: "Clifton Downs", city: "Bristol", foodAndBeverage: "The Downs Cafe", parking: false, toilets: true,  disableAccess: true, imgs: ["https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/The_Downs%2C_Bristol_(2272).jpg/800px-The_Downs%2C_Bristol_(2272).jpg","https://visitbristol.co.uk/dbimgs/ARE-CLI-Clifton-Downs_CREDIT_Destination-Bristol%20(6).jpg","https://visitbristol.co.uk/dbimgs/ARE-CLI-Clifton-Downs_CREDIT_Destination-Bristol%20(4)(1).jpg","https://i.pinimg.com/736x/3e/7b/71/3e7b716e0a40371290f14aa354581c2a--the-bristol-suspension-bridge.jpg"]},
   {name: "Hyde Park", city: "London", foodAndBeverage: "Serpentine Bar & Kitchen and more",parking: true, toilets: true, disableAccess: true, imgs: ["http://vizts.com/wp-content/uploads/2016/03/hyde-park-london.jpg","http://1.bp.blogspot.com/-DOKmlBYq_WY/UUi-d0Q7woI/AAAAAAAAGoI/3blIIJnYYLM/s1600/Hyde+Park+London-3.jpg","https://www.parkgrandhydepark.co.uk/blog/wp-content/uploads/2014/08/shutterstock_211607107.jpg", "https://www.grandroyalelondon.co.uk/blog/wp-content/uploads/2019/06/walk-in-the-Hyde-park-in-London.jpg"]},
   {name: "Kensington Gardens", city: "London", foodAndBeverage: "The Italian Gardens Cafe and more",parking: false, toilets: true, disableAccess: true, imgs: ["https://i.pinimg.com/originals/d1/6d/e5/d16de58b66918b170eb93d4b0ac70fed.jpg","https://i.pinimg.com/originals/5d/6e/ce/5d6ece9f89118b43fdb630859e4d4e22.jpg","https://www.royalparks.org.uk/parks/kensington-gardens/things-to-see-and-do/memorials-fountains-and-statues/kensington-gardens-bandstand/_gallery/The-Royal-Parks_Kensington-Gardens__Bandstand-2_.jpg/w_1200.jpg"]},
   {name: "The Regent's Park", city: "London", foodAndBeverage: "The broad walk cafe and more",parking: true, toilets: true, disableAccess: true, imgs: ["https://secureservercdn.net/160.153.138.71/l4u.6ce.myftpupload.com/wp-content/uploads/2019/05/location-Regents-Park-London.jpg?time=1580853460","https://si.wsj.net/public/resources/images/MN-AH449_REGENT_M_20141021170404.jpg","https://i.pinimg.com/originals/e9/a3/46/e9a3469c7c0eecdd5fe7d94bf78092cb.jpg"]},
   {name: "Victoria Tower Gardens", city: "London", foodAndBeverage: null,parking: false, toilets: false, disableAccess: true, imgs: ["http://contactdir.uk/wp-content/uploads/2017/07/Playground-Victoria-Tower-Gardens.jpg","https://hbpge.hall-mccartney.co.uk/wp-content/uploads/Buxton-Memorial-at-Victoria-Tower-Gardens-by-Sally-Prothero-v3.jpg"]},
];

module.exports = parks;
